-- Lab 3, Issue 32 — Authentication foundation.
--
-- Renames RequesterUser -> User IN PLACE (same table, same primary keys), so
-- every existing Ticket.requesterId foreign key stays valid across the
-- migration (specification.md §7, migration path steps 1-4). This file was
-- hand-written, not generated by `prisma migrate dev`'s diff engine, because
-- a same-shape rename is otherwise indistinguishable from "drop and
-- recreate" to that engine — which would have deleted every seeded/created
-- Requester and, via ON DELETE RESTRICT, failed or cascaded into Tickets.
--
-- A full pg_dump backup was taken before this file ran (repo-root
-- db-backups/, gitignored, never a deliverable) per the Lab 3 briefing's
-- explicit pre-migration-backup requirement.

-- Step 1 — rename the table and its dependent objects to match what a fresh
-- `prisma generate` would name a model called User (verified against the
-- real object names in the dev DB via `psql \d "RequesterUser"` first).
ALTER TABLE "RequesterUser" RENAME TO "User";
ALTER TABLE "User" RENAME CONSTRAINT "RequesterUser_pkey" TO "User_pkey";
ALTER INDEX "RequesterUser_email_key" RENAME TO "User_email_key";
ALTER SEQUENCE "RequesterUser_id_seq" RENAME TO "User_id_seq";

-- Step 2 — new Role enum.
CREATE TYPE "Role" AS ENUM ('REQUESTER', 'IT_STAFF', 'ADMINISTRATOR');

-- Steps 2-4 (add + backfill + require) collapse into one statement per
-- column: Postgres 11+ applies a constant DEFAULT to existing rows as a
-- metadata-only operation, so ADD COLUMN ... NOT NULL DEFAULT <constant> is
-- both the backfill and the constraint in a single atomic step. The default
-- is then dropped so every *future* row must supply an explicit value from
-- application code (seed.ts / the Administrator "create user" route) —
-- mustChangePassword is the one exception, where defaulting new rows to
-- "must change password" is the correct permanent behavior, matching
-- schema.prisma's `@default(true)`.
ALTER TABLE "User" ADD COLUMN "role" "Role" NOT NULL DEFAULT 'REQUESTER';
ALTER TABLE "User" ALTER COLUMN "role" DROP DEFAULT;

ALTER TABLE "User" ADD COLUMN "mustChangePassword" BOOLEAN NOT NULL DEFAULT true;

-- passwordHash's backfill default is a REAL bcrypt (cost 12) hash — via
-- pgcrypto's blowfish crypt(), which produces the same $2a$/$2b$ modular
-- crypt format the Node `bcryptjs` library at runtime reads and verifies —
-- of the documented local-dev initial password 'ChangeMe123!' (see
-- README.md "Local development credentials"). This is a fixture password,
-- never a real secret, and every migrated account has mustChangePassword
-- forced to true above so it cannot be used past first login.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

ALTER TABLE "User" ADD COLUMN "passwordHash" TEXT NOT NULL
  DEFAULT crypt('ChangeMe123!', gen_salt('bf', 12));
ALTER TABLE "User" ALTER COLUMN "passwordHash" DROP DEFAULT;

ALTER TABLE "User" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "User" ALTER COLUMN "updatedAt" DROP DEFAULT;
